orbs:
  cypress: cypress-io/cypress@1
version: 2.1

# have a look at https://circleci.com/orbs/registry/orb/germade/rsync
executors:
  cypress-executor:
    docker:
      - image: "cypress/included:4.10.0"
    resource_class: large

jobs:
  deploy:
    docker:
      - image: instrumentisto/rsync-ssh
    resource_class: large
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run: eval ssh-agent -s
      - run:
          name: Transfer build to digital ocean instance
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST_PROD_1" exit
              rsync -O -ave ssh ~/project/build "$SSH_PROD_USER"@"$SSH_HOST_PROD_1":/home/oipa/oipa-query-builder
              ssh "$SSH_PROD_USER"@"$SSH_HOST_PROD_1" "/home/oipa/ci_update_front.sh;"
              ssh -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST_PROD_2" exit
              rsync -O -ave ssh ~/project/build "$SSH_PROD_USER"@"$SSH_HOST_PROD_2":/home/oipa/oipa-query-builder
              ssh "$SSH_PROD_USER"@"$SSH_HOST_PROD_2" "/home/oipa/ci_update_front.sh;"
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ssh -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST_DEV" exit
              rsync -O -ave ssh ~/project/build "$SSH_USER"@"$SSH_HOST_DEV":~/stg-iati-cloud-front
              ssh "$SSH_USER"@"$SSH_HOST_DEV" "./ci_update_front.sh;"
            else
              ssh -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST_DEV" exit
              rsync -O -ave ssh ~/project/build "$SSH_USER"@"$SSH_HOST_DEV":~/stg-iati-cloud-front
              ssh "$SSH_USER"@"$SSH_HOST_DEV" "./ci_update_front.sh;"
            fi

  release:
    docker:
      - image: circleci/node:12.14.1-stretch-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run: npx semantic-release

workflows:
  build-and-test:
    jobs:
      - cypress/install:
          name: "checkout"
          executor: cypress-executor
          pre-steps:
            - run:
                name: Set env variables
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    echo 'export REACT_APP_DOC_FILENAME="$REACT_APP_POSTMAN_FILENAME_PROD"' >> $BASH_ENV
                  elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                    echo 'export REACT_APP_DOC_FILENAME="$REACT_APP_POSTMAN_FILENAME_STG"' >> $BASH_ENV
                  else
                    echo 'export REACT_APP_DOC_FILENAME="$REACT_APP_POSTMAN_FILENAME_STG"' >> $BASH_ENV
                  fi
                  source $BASH_ENV
          yarn: true
          build: yarn build

      # - cypress/run:
      #     name: "local e2e tests"
      #     executor: cypress-executor
      #     pre-steps:
      #       - run:
      #           name: Set env variables
      #           command: |
      #               echo 'export CYPRESS_BASE_URL="http://localhost:3000"' >> $BASH_ENV
      #             source $BASH_ENV
      #     wait-on: "http://localhost:3000"
      #     yarn: true
      #     start: yarn start:ci
      #     browser: chrome
      #     requires:
      #       - deploy
      #     record: true
      #     parallel: true
      #     parallelism: 5
      #     group: "all tests"
      #
      - deploy:
          requires:
            - "checkout"
            # - "local e2e tests"

      - cypress/run:
          name: "deployed e2e tests"
          executor: cypress-executor
          pre-steps:
            - run:
                name: Set env variables
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    echo 'export CYPRESS_BASE_URL="https://iatidatastore.iatistandard.org"' >> $BASH_ENV
                  elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                    echo 'export CYPRESS_BASE_URL="https://store.staging.iati.cloud"' >> $BASH_ENV
                  else
                    echo 'export CYPRESS_BASE_URL="https://store.staging.iati.cloud"' >> $BASH_ENV
                  fi
                  source $BASH_ENV
          yarn: true
          command: yarn happo-cypress -- -- yarn cypress run --record --parallel
          browser: chrome
          requires:
            - deploy
          record: true
          parallel: true
          parallelism: 5
          group: "all tests"

      - release:
          requires:
            - deploy
          filters:
            branches:
              only: master
