export const activityFields = [
  { code: 'url', name: 'URL' },
  { code: 'id', name: 'ID' },
  { code: 'iati_identifier', name: 'IATI Identifier' },
  { code: 'reporting_organisation', name: 'Reporting Organization' },
  { code: 'title', name: 'Title' },
  { code: 'descriptions', name: 'Descriptions' },
  { code: 'participating_organisation', name: 'Participating Organization' },
  { code: 'other_identifier', name: 'Other Identifier' },
  { code: 'activity_status', name: 'Activity Status' },
  { code: 'budget_not_provided', name: 'Budget not provided' },
  { code: 'activity_dates', name: 'Activity Dates' },
  { code: 'contact_info', name: 'Contact Information' },
  { code: 'activity_scope', name: 'Activity Scope' },
  { code: 'recipient_countries', name: 'Recipient Countries' },
  { code: 'recipient_regions', name: 'Recipient Regions' },
  { code: 'locations', name: 'Locations' },
  { code: 'sectors', name: 'Sectors' },
  { code: 'tag', name: 'Tag' },
  { code: 'country_budget_items', name: 'Country Budget Items' },
  { code: 'humanitarian', name: 'Humanitarian' },
  { code: 'humanitarian_scope', name: 'Humanitarian Scope' },
  { code: 'policy_markers', name: 'Policy Markers' },
  { code: 'collaboration_type', name: 'Collaboration Type' },
  { code: 'default_flow_type', name: 'Default Flow Type' },
  { code: 'default_finance_type', name: 'Default Finance Type' },
  { code: 'default_aid_type', name: 'Default Aid Type' },
  { code: 'default_tied_status', name: 'Default Aid Status' },
  { code: 'budgets', name: 'Budgets' },
  { code: 'planned_disbursements', name: 'Planned Disbursements' },
  { code: 'capital_spend', name: 'Capital Spend' },
  { code: 'transactions', name: 'Transactions' },
  { code: 'related_transactions', name: 'Related Transactions' },
  { code: 'document_links', name: 'Document Links' },
  { code: 'related_activities', name: 'Related Activities' },
  { code: 'legacy_data', name: 'Legacy Data' },
  { code: 'conditions', name: 'Conditions' },
  { code: 'results', name: 'Results' },
  { code: 'crs_add', name: 'CRS Add' },
  { code: 'fss', name: 'FSS' },
  { code: 'last_updated_datetime', name: 'Last Updated Datetime' },
  { code: 'xml_lang', name: 'XML language' },
  { code: 'default_currency', name: 'Default Currency' },
  { code: 'hierarchy', name: 'Hierarchy' },
  { code: 'linked_data_uri', name: 'Linked Data URI' },
  { code: 'secondary_reporter', name: 'Secondary reporter' },
  { code: 'aggregations', name: 'Aggregations' },
  { code: 'dataset', name: 'Dataset' },
  { code: 'publisher', name: 'Publisher' },
  { code: 'published_state', name: 'Published state' },
  { code: 'transaction_types', name: 'Transaction Types' },
];

export const transactionFields = [
  { code: 'iati_identifier', name: 'IATI Identifier' },
  { code: 'sectors', name: 'Sectors' },
  { code: 'recipient_countries', name: 'Recipient Countries' },
  { code: 'recipient_regions', name: 'Recipient Regions' },
  { code: 'url', name: 'URL' },
  { code: 'transaction_type', name: 'Transaction Type' },
  { code: 'value', name: 'Value' },
  { code: 'provider_organisation', name: 'Provider Organization' },
];

export const budgetFields = [
  { code: 'iati_identifier', name: 'IATI Identifier' },
  { code: 'sectors', name: 'Sectors' },
  { code: 'recipient_countries', name: 'Recipient Countries' },
  { code: 'recipient_regions', name: 'Recipient Regions' },
  { code: 'id', name: 'ID' },
  { code: 'type', name: 'Type' },
  { code: 'value', name: 'Value' },
  { code: 'status', name: 'Status' },
  { code: 'period_start', name: 'Period start' },
  { code: 'period_end', name: 'Period end' },
  { code: 'xdr_value', name: 'XDR Value' },
  { code: 'usd_value', name: 'USD Value' },
  { code: 'eur_value', name: 'EUR Value' },
  { code: 'gbp_value', name: 'GBP Value' },
  { code: 'jpy_value', name: 'JPY Value' },
  { code: 'cad_value', name: 'CAD Value' },
  { code: 'activity_id', name: 'Activity ID' },
];

export const groupedOptions = [
  {
    label: 'Activities',
    options: activityFields,
    tip: " (change 'Row format' selection to 'Each Unique Activity')",
  },
  {
    label: 'Transactions',
    options: transactionFields,
    tip: " (change 'Row format' selection to 'Each Financial Transaction')",
  },
  {
    label: 'Budgets',
    options: budgetFields,
    tip: " (change 'Row format' selection to 'Each Budget In Defined Periods')",
  },
];
